
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGVD3vwBgKWeJKbrH81Mg1rAHnmFPjYc',
    appId: '1:752312152785:web:44adfb2793dafe73b5cbf0',
    messagingSenderId: '752312152785',
    projectId: 'hospital-registration-sy-a1b04',
    authDomain: 'hospital-registration-sy-a1b04.firebaseapp.com',
    storageBucket: 'hospital-registration-sy-a1b04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl6eTCfq_0Fu71qoVwK6cg1_LnGx2fBPU',
    appId: '1:752312152785:android:37d51278b6f7e4c5b5cbf0',
    messagingSenderId: '752312152785',
    projectId: 'hospital-registration-sy-a1b04',
    storageBucket: 'hospital-registration-sy-a1b04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4qTxV9c1qUOwPfIl0flhf70471ubaX50',
    appId: '1:752312152785:ios:e5f5a6502790afb3b5cbf0',
    messagingSenderId: '752312152785',
    projectId: 'hospital-registration-sy-a1b04',
    storageBucket: 'hospital-registration-sy-a1b04.appspot.com',
    iosBundleId: 'com.example.hospitalRegistrationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4qTxV9c1qUOwPfIl0flhf70471ubaX50',
    appId: '1:752312152785:ios:e5f5a6502790afb3b5cbf0',
    messagingSenderId: '752312152785',
    projectId: 'hospital-registration-sy-a1b04',
    storageBucket: 'hospital-registration-sy-a1b04.appspot.com',
    iosBundleId: 'com.example.hospitalRegistrationSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChGVD3vwBgKWeJKbrH81Mg1rAHnmFPjYc',
    appId: '1:752312152785:web:3bce1237dd04564eb5cbf0',
    messagingSenderId: '752312152785',
    projectId: 'hospital-registration-sy-a1b04',
    authDomain: 'hospital-registration-sy-a1b04.firebaseapp.com',
    storageBucket: 'hospital-registration-sy-a1b04.appspot.com',
  );
}

